# @todo #156:15min Add smtp server config
#   Add smtp configuration
spring:
  application:
    name: qa-admin
    jwt:
      secret-key:
        6E5A7234753778214125442A472D4B6150645367566B59703373357638792F42
      expiration: 86400000 # a day
      refresh-token:
        expiration: 604800000 # 7 days
  datasource:
    username: ${POSTGRES_USER}
    password: ${POSTGRES_PASSWORD}
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://${POSTGRES_HOST}:${POSTGRES_PORT}/postgres
  jpa:
    hibernate:
      ddl-auto: none
    open-in-view: false
  mail:
    host: ${SMTP_HOST}
    port: ${SMTP_PORT}
    properties:
      mail:
        smtp:
          auth: false
          starttls:
            enable: false
server:
  port: ${QA_ADMIN_PORT}
answer:
  answered-subject:
    Ответ на Ваш вопрос добавлен
  removed-subject:
    Ваш вопрос был отклонен
  answered-template:
    Мы добавили ответ на Ваш вопрос '%s' в чат!
  removed-template:
    К сожалению, мы не можем ответить на Ваш вопрос!
  from:
    volpi@mail.ru